import {
    IconBook,
    IconHeadphones,
    IconCamera,
    IconDeviceGamepad2,
    IconFeather,
    IconMoodSmile,
    IconArrowLeft,
    IconChevronLeft,
    IconChevronDown,
    IconChevronUp,
    IconShare,
    IconFileText,
    IconTargetArrow,
    IconPresentation,
    IconPlayerPlay,
    IconPlayerPause,
    IconHeart,
    IconUser,
    IconSettings,
    IconChevronRight,
    IconBell,
    IconMoon,
    IconLanguage,
    IconCreditCard,
    IconShield,
    IconInfoCircle,
    IconHelp,
    IconLock,
    IconBrandGoogle,
    IconBrandApple,
    IconEye,
    IconEyeOff,
    IconX,
    IconPencil,
    IconRefresh,
    IconCheck,
    IconMaximize,
    IconMinimize,
    IconAlertCircle,
    IconVolume,
    IconVolumeOff,
    IconMessageCircle,
    IconArrowRight,
} from '@tabler/icons-react';

export const Icons = {
    book: IconBook,
    podcast: IconHeadphones,
    photos: IconCamera,
    games: IconDeviceGamepad2,
    opinion: IconFeather,
    cartoons: IconMoodSmile,
    back: IconArrowLeft,
    share: IconShare,
    original: IconFileText,
    summary: IconTargetArrow,
    guided: IconPresentation,
    play: IconPlayerPlay,
    pause: IconPlayerPause,
    heart: IconHeart,
    user: IconUser,
    settings: IconSettings,
    chevronRight: IconChevronRight,
    chevronLeft: IconChevronLeft,
    bell: IconBell,
    moon: IconMoon,
    language: IconLanguage,
    subscription: IconCreditCard,
    privacy: IconShield,
    info: IconInfoCircle,
    help: IconHelp,
    lock: IconLock,
    google: IconBrandGoogle,
    apple: IconBrandApple,
    eye: IconEye,
    eyeOff: IconEyeOff,
    x: IconX,
    edit: IconPencil,
    refresh: IconRefresh,
    check: IconCheck,
    maximize: IconMaximize,
    minimize: IconMinimize,
    alertCircle: IconAlertCircle,
    arrowLeft: IconArrowLeft,
    volume: IconVolume,
    volumeOff: IconVolumeOff,
    chevronDown: IconChevronDown,
    chevronUp: IconChevronUp,
    comment: IconMessageCircle,
    arrowRight: IconArrowRight,
};
